// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpgvuxD281HKKi1Cqoc8GBFlWLeEvFLN0',
    appId: '1:75513311741:web:386f11bb4f9b0837a92994',
    messagingSenderId: '75513311741',
    projectId: 'citymallonline-8770e',
    authDomain: 'citymallonline-8770e.firebaseapp.com',
    storageBucket: 'citymallonline-8770e.appspot.com',
    measurementId: 'G-YNW9X4DFJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQYn7mXFO0XhLWL7nSbAOXP8SfmJbyhjw',
    appId: '1:75513311741:android:e7c7f5d2a45c6082a92994',
    messagingSenderId: '75513311741',
    projectId: 'citymallonline-8770e',
    storageBucket: 'citymallonline-8770e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-VC-TO2e9Qz4WbYXT5RqOJd995Tphv8M',
    appId: '1:75513311741:ios:943653c8a54e7d96a92994',
    messagingSenderId: '75513311741',
    projectId: 'citymallonline-8770e',
    storageBucket: 'citymallonline-8770e.appspot.com',
    iosClientId: '75513311741-kvv66o6cegjvmllqsm8rhosjprrk6b79.apps.googleusercontent.com',
    iosBundleId: 'com.example.citymallonline',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA-VC-TO2e9Qz4WbYXT5RqOJd995Tphv8M',
    appId: '1:75513311741:ios:943653c8a54e7d96a92994',
    messagingSenderId: '75513311741',
    projectId: 'citymallonline-8770e',
    storageBucket: 'citymallonline-8770e.appspot.com',
    iosClientId: '75513311741-kvv66o6cegjvmllqsm8rhosjprrk6b79.apps.googleusercontent.com',
    iosBundleId: 'com.example.citymallonline',
  );
}
